### PR TITLE
Update aes to 0.8, replace deprecated block-modes with cbc

### PR DESCRIPTION
**Pull request by nc7s**

### CODE REVIEW

**Comment by complexspaces** [comment]
Thanks for this. Would you mind rebasing these changes on `master` in a day or two once I merge #58 this week? It also touches the same code area so there will be conflicts.

**Comment by complexspaces** [comment]
@bnoctis I've merged that PR, and some CI fixes, into `master` earlier today so you should be able to rebase now. I'll be happy to start review after that (even though at a glance, it seems like everything is fine).

**Comment by bnoctis** [comment]
@complexspaces done, please approve the actions run so we can see if it passes tests; I have to add `--features=rt-async-io-crypto-rust` to let it compile locally before tests start to run.

**Comment by bnoctis** [comment]
Any news? 😃

**Comment by nc7s** [comment]
Closing for now. Ping me if still interested.

**Comment by complexspaces** [comment]
@nc7s Hi again, I apologize for going quiet here. This repository is usually the first to fall off when I get busy.

Are you still interested in merging this? I should have the bandwidth to help you get this one landed and released on crates.io.

**Pull request closed without merging**
