### PR TITLE
chore: Update dbus to 0.6

### PR DESCRIPTION
**Pull request by ignatenkobrain**

### CODE REVIEW

**Comment by ignatenkobrain** [comment]
Oh, this is more complicated... I would appreciate help.

**Comment by hwchen** [comment]
Yup :) this is why I haven’t updated the dependency yet. There’s no particular help to offer, but I think that every struct will need to be altered. Unless there’s a bug, I’d probably hold off on this until I have time to do myself.

**Comment by liamdawson** [comment]
I've run into a relevant issue: `dbus::Error` doesn't implement `Sync` in v0.2.0, which is preventing me from using `anyhow::Context` on errors from this library when compiling on Ubuntu.

**Comment by hwchen** [comment]
Ah, sorry this is an issue. I haven't had much time lately to devote to further maintenance, but updating dbus is definitely on my radar.

**Comment by hwchen** [comment]
I'll be closing this in favor of a port to zbus. We can revisit if the port doesn't work out.

**Pull request closed without merging**
