### PR TITLE
Bump rust-gmp to 0.3 to fix build on nightly rustc

### PR DESCRIPTION
**Pull request by petrochenkov**
Hi.
https://github.com/rust-lang/rust/pull/42125 is going to turn some old compatibility "private-in-public" warnings in `rustc` into hard errors.
`crates.io` testing discovered that this crate uses an old version of `rust-gmp` affected by one of those errors.
This PR updates `rust-gmp` to 0.3, which is the minimal version building successfully with https://github.com/rust-lang/rust/pull/42125

### CODE REVIEW

**Comment by hwchen** [comment]
Thanks! Will merge shortly.

**Comment by petrochenkov** [comment]
@hwchen 
Could you also publish the updated version to crates.io as `secret-service-0.3.2`?

**Comment by hwchen** [comment]
Yup, getting to it this morning, didn't have quite enough time last night.
Thanks!

On Jun 6, 2017 4:46 AM, "Vadim Petrochenkov" <notifications@github.com>
wrote:

@hwchen <https://github.com/hwchen>
Could you also publish the updated version to crates.io as
secret-service-0.3.2?

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/hwchen/secret-service-rs/pull/2#issuecomment-306422168>,
or mute the thread

**Comment by hwchen** [comment]
published! as 0.4.0, because of a more major change in #1

**Comment by petrochenkov** [comment]
Thanks!

**Pull request merged**
