### PR TITLE
update dependencies where no code changes are necessary

### PR DESCRIPTION
**Pull request by decathorpe**
- update dependencies where no code changes are necessary
- crate builds and tests pass (at least locally)

### CODE REVIEW

**Comment by repi** [comment]
Would be great to merge this in and publish a new crate!

**Comment by hwchen** [comment]
Will do soon! Sorry, I've been super busy lately, but I'll try to get this
out next week.

**Comment by repi** [comment]
@hwchen sorry to nag, but any update on this? Anything we ([Embark](https://embark.games)) can help with? we use this crate through `keyring` that I noticed you just released an update for (thanks!).

**Comment by hwchen** [comment]
oh, thanks for the ping. I had lost track of this.

**Comment by hwchen** [comment]
I'll be updating keyring deps shortly, just need to figure out if an issue with the latest release is in CI or otherwise.

**Comment by repi** [comment]
Thanks!

**Comment by hwchen** [comment]
keyring v0.10.1 is out with new secret-service version. Ended up mucking about with CI and tests, and that took up more time than expected.

**Comment by repi** [comment]
Thanks!

**Pull request merged**
