### PR TITLE
allow creation w/ dbus name

### LINKED ISSUE #18: Allow changing of dbus name?
When trying to run a flatpak'd application, this crate will fail with `unable to store token: SecretServiceError(Dbus(D-Bus error: org.freedesktop.DBus.Error.ServiceUnknown (org.freedesktop.DBus.Error.ServiceUnknown)))` if the application is not allowed to talk to the host secrets dbus. Flatpak does, however, provide a local dbus portal which stores the keychain on the application side (see https://github.com/flatpak/xdg-desktop-portal/) for more. Would it be possible to allow configuring the dbus name to something other than the default? In this case, it would be `org.freedesktop.portal.secrets`, or similar.

### PR DESCRIPTION
**Pull request by hwchen**
Create a session with dbus name. Closes #18.

### CODE REVIEW

**Comment by hwchen** [comment]
@Restioson does this work for you? (sorry it took a while for to get to!)

**Comment by Restioson** [comment]
Hi, thanks for the update :) I will test it

**Comment by hwchen** [comment]
@Restioson just wanted to check if this was still going to be useful to you

**Comment by Restioson** [comment]
Hi :) Sorry for not testing it, I have been busy with my studies. I probably will not use it soon but maybe it is useful for others?

**Comment by hwchen** [comment]
I'm going to close this for now, until there's somebody who can champion and test this. Want to make sure there's real-world use so I don't miss something.

**Pull request closed without merging**
